export const translations = {
  en: {
    name: 'English',
    political: "Political",
    population: "Population",
    claims: "Claims",
    nationPopulation: "Nation Population",
    nationClaims: "Nation Claims",
    founded: "Foundation Date",
    density: "Density",
    legend: "Legend",
    language: "Language",
    oldest: "Oldest",
    newest: "Newest",
    popChunk: "pop/chunk",
    noLegend: "No legend available for Political mode",
    mayor: "Mayor",
    councillors: "Councillors",
    pvp: "PVP",
    public: "Public",
    nation: "Nation",
    nationClaimsLabel: "Nation Claims",
    nationPopLabel: "Nation Pop",
    loading: "Loading map data...",
    error: "Error loading map data. Please try again later."
  },
  ja: {
    name: '日本語',
    political: "政治的",
    population: "人口",
    claims: "チャンク",
    nationPopulation: "国の人口",
    nationClaims: "国のチャンク",
    founded: "設立日",
    density: "人口密度",
    legend: "凡例",
    language: "言語",
    oldest: "最古",
    newest: "最新",
    popChunk: "人/チャンク",
    noLegend: "このモードでは凡例は使用できません",
    mayor: "市長",
    councillors: "評議員",
    pvp: "PVP",
    public: "パブリック",
    nation: "国",
    nationClaimsLabel: "国のチャンク",
    nationPopLabel: "国の人口",
    loading: "マップデータを読み込み中...",
    error: "マップデータの読み込み中にエラーが発生しました。後でもう一度お試しください。"
  },
  fr: {
    name: 'Français',
    political: "Politique",
    population: "Population",
    claims: "Territoire",
    nationPopulation: "Population de la Nation",
    nationClaims: "Territoire de la Nation",
    founded: "Date de Fondation",
    density: "Densité",
    legend: "Légende",
    language: "Langue",
    oldest: "Plus ancien",
    newest: "Plus récent",
    popChunk: "hab/chunk",
    noLegend: "Pas de légende disponible pour le mode Politique",
    mayor: "Maire",
    councillors: "Conseillers",
    pvp: "PVP",
    public: "Public",
    nation: "Nation",
    nationClaimsLabel: "Territoire Nation",
    nationPopLabel: "Pop Nation",
    loading: "Chargement des données de la carte...",
    error: "Erreur lors du chargement des données de la carte. Veuillez réessayer plus tard."
  }
};
