export const translations = {
  en: {
    name: "English",
    political: "Political",
    population: "Population",
    claims: "Claims",
    claimLimit: "Claim Limit",
    nationPopulation: "Nation Population",
    nationClaims: "Nation Claims",
    founded: "Foundation Date",
    density: "Density",
    legend: "Legend",
    language: "Language",
    settings: "Settings",
    oldest: "Oldest",
    newest: "Newest",
    underLimit: "Under Limit",
    atLimit: "At Limit",
    overLimit: "Over Limit",
    shield: "Shield",
    shieldActive: "Overclaim Shield Active",
    popChunk: "pop/chunk",
    noLegend: "No legend available for Political mode",
    mayor: "Mayor",
    councillors: "Councillors",
    pvp: "PVP",
    public: "Public",
    nation: "Nation",
    chunkGrid: "Chunk Grid",
    nationClaimsLabel: "Nation Claims",
    nationPopLabel: "Nation Pop",
    nationTownsLabel: "Nation Towns",
    nationLeader: "Leader",
    nationCapital: "Capital",
    board: "Board",
    loading: "Loading map data...",
    error: "Error loading map data. Please try again later.",
    rankings: "Rankings",
    populationRank: "Population Rank",
    claimsRank: "Claims Rank",
    top1: "Top 1",
    top3: "Top 3",
    top10: "Top 10",
    valueGradient: "Value Gradient",
    oldestDay: "First Day",
    oldest7Days: "Oldest 7 Days",
    oldest28Days: "Oldest 28 Days",
    townData: "Town Data",
    rankingsOutlines: "Rankings Outlines"
  },
  ja: {
    name: "日本語",
    political: "政治的",
    population: "人口",
    claims: "チャンク",
    claimLimit: "チャンク制限",
    nationPopulation: "国の人口",
    nationClaims: "国のチャンク",
    founded: "設立日",
    density: "人口密度",
    legend: "凡例",
    language: "言語",
    settings: "設定",
    oldest: "最古",
    newest: "最新",
    underLimit: "制限以下",
    atLimit: "限界で",
    overLimit: "制限以上",
    shield: "保護",
    shieldActive: "オーバークレーム保護あり",
    popChunk: "人/チャンク",
    noLegend: "このモードでは凡例は使用できません",
    mayor: "市長",
    councillors: "評議員",
    pvp: "PVP",
    public: "パブリック",
    nation: "国",
    chunkGrid: "チャンクグリッド",
    nationClaimsLabel: "国のチャンク",
    nationPopLabel: "国の人口",
    nationTownsLabel: "国の町",
    nationLeader: "リーダー",
    nationCapital: "首都",
    board: "メッセージ",
    loading: "マップデータを読み込み中...",
    error: "マップデータの読み込み中にエラーが発生しました。後でもう一度お試しください。",
    rankings: "ランキング",
    populationRank: "人口ランク",
    claimsRank: "チャンクランク",
    top1: "トップ1",
    top3: "トップ3",
    top10: "トップ10",
    valueGradient: "値グラデーション",
    oldestDay: "最古の日",
    oldest7Days: "最古の7日",
    oldest28Days: "最古の28日",
    townData: "町データ",
    rankingsOutlines: "ランキングアウトライン"
  },
  fr: {
    name: "Français",
    political: "Politique",
    population: "Population",
    claims: "Territoire",
    claimLimit: "Limite de Territoire",
    nationPopulation: "Population de la Nation",
    nationClaims: "Territoire de la Nation",
    founded: "Date de Fondation",
    density: "Densité",
    legend: "Légende",
    language: "Langue",
    settings: "Paramètres",
    oldest: "Plus ancien",
    newest: "Plus récent",
    underLimit: "Sous la limite",
    atLimit: "À la limite",
    overLimit: "Au dessus de la limite",
    shield: "Protection",
    shieldActive: "Protection Overclaim Active",
    popChunk: "hab/chunk",
    noLegend: "Pas de légende disponible pour le mode Politique",
    mayor: "Maire",
    councillors: "Conseillers",
    pvp: "PVP",
    public: "Public",
    nation: "Nation",
    chunkGrid: "Grille des Chunks",
    nationClaimsLabel: "Territoire Nation",
    nationPopLabel: "Pop Nation",
    nationTownsLabel: "Villes Nation",
    nationLeader: "Leader",
    nationCapital: "Capitale",
    board: "Message",
    loading: "Chargement des données de la carte...",
    error: "Erreur lors du chargement des données de la carte. Veuillez réessayer plus tard.",
    rankings: "Classements",
    populationRank: "Rang de Population",
    claimsRank: "Rang de Territoire",
    top1: "Top 1",
    top3: "Top 3",
    top10: "Top 10",
    valueGradient: "Gradient de Valeur",
    oldestDay: "Premier Jour",
    oldest7Days: "Plus Anciens 7 Jours",
    oldest28Days: "Plus Anciens 28 Jours",
    townData: "Données de Ville",
    rankingsOutlines: "Contours des Classements"
  },
  id: {
    name: "Bahasa Indonesia",
    political: "Geopolitik",
    population: "Populasi",
    claims: "Luas Teritori",
    claimLimit: "Batas Klaim Teritori",
    nationPopulation: "Populasi Negara",
    nationClaims: "Luas Teritori Negara",
    founded: "Tanggal Berdiri",
    density: "Kepadatan",
    legend: "Legenda",
    language: "Bahasa",
    settings: "Pengaturan",
    oldest: "Terlama",
    newest: "Terbaru",
    underLimit: "Di bawah batas",
    atLimit: "Tepat pada batas",
    overLimit: "Melebihi batas",
    shield: "Shield", // todo
    shieldActive: "Overclaim Shield Active", // todo
    popChunk: "Populasi/Luas Teritori",
    noLegend: "Tidak ada legenda di mode Geopolitik",
    mayor: "Walikota",
    councillors: "Anggota Dewan",
    pvp: "PVP",
    public: "Publik",
    nation: "Negara",
    chunkGrid: "Garis Perbatasan Chunk",
    nationClaimsLabel: "Luas Teritori Negara",
    nationPopLabel: "Populasi Negara",
    nationTownsLabel: "Nation Towns", // todo
    nationLeader: "Leader", // todo
    nationCapital: "Capital", // todo
    loading: "Memuat Data pada Peta",
    error: "Gagal memuat data. Silahkan coba lagi nanti.",
    rankings: "Rankings", // todo
    populationRank: "Population Rank", // todo
    claimsRank: "Claims Rank", // todo
    top1: "Top 1", // todo
    top3: "Top 3", // todo
    top10: "Top 10", // todo
    valueGradient: "Value Gradient", // todo
    oldestDay: "First Day", // todo
    oldest7Days: "Oldest 7 Days", // todo
    oldest28Days: "Oldest 28 Days", // todo
    townData: "Town Data", // todo
    rankingsOutlines: "Rankings Outlines" // todo
  },
  hi: {
    name: "हिंदी",
    political: "राजनीतिक",
    population: "जनसंख्या",
    claims: "दावे",
    claimLimit: "दावों की सीमा",
    nationPopulation: "राष्ट्र की जनसंख्या",
    nationClaims: "राष्ट्र के दावे",
    founded: "स्थापना की तारीख",
    density: "घनत्व",
    legend: "संकेत-सूची",
    language: "भाषा",
    settings: "सेटिंग्स",
    oldest: "सबसे पुराना",
    newest: "सबसे नया",
    underLimit: "सीमा के अंदर",
    atLimit: "सीमा पर",
    overLimit: "सीमा से ज़्यादा",
    shield: "Shield", // todo
    shieldActive: "Overclaim Shield Active", // todo
    popChunk: "पापुलेशन/चंक",
    noLegend: "राजनीतिक मोड के लिए कोई संकेत-सूची उपलब्ध नहीं है",
    mayor: "मेयर",
    councillors: "पार्षद",
    pvp: "पीवीपी",
    public: "सार्वजनिक",
    nation: "राष्ट्र",
    chunkGrid: "चंक ग्रिड",
    nationClaimsLabel: "राष्ट्र के दावे",
    nationPopLabel: "राष्ट्र की जनसंख्या",
    nationTownsLabel: "राष्ट्र के शहर",
    nationLeader: "नेता",
    nationCapital: "राजधानी",
    board: "बोर्ड",
    loading: "मैप डेटा लोड हो रहा है...",
    error: "मैप डेटा लोड करने में त्रुटि हुई। कृपया बाद में फिर से प्रयास करें।",
    rankings: "Rankings", // todo
    populationRank: "Population Rank", // todo
    claimsRank: "Claims Rank", // todo
    top1: "Top 1", // todo
    top3: "Top 3", // todo
    top10: "Top 10", // todo
    valueGradient: "Value Gradient", // todo
    oldestDay: "First Day", // todo
    oldest7Days: "Oldest 7 Days", // todo
    oldest28Days: "Oldest 28 Days", // todo
    townData: "Town Data", // todo
    rankingsOutlines: "Rankings Outlines" // todo
  },
};
